### ISSUE TITLE
TF_REPEATED_DATA warning

### ISSUE THREAD

**Issue by jsbyysheng** [jhu-saw/sawNDITracker#14]
In ubuntu 20.04 + ros noetic, I continuously got `Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame` when using Aurora. This warning can be related to [New warning message for repeated transforms #467](https://github.com/ros/geometry2/issues/467) and I suggest doing some modifications for this package.

**Comment by adeguet1** [comment]
Can you test this patch: https://github.com/jhu-cisst/cisst-ros/commit/3e997ff12586a9be5f8e7744435adc389c70fa4b
You will need all repositories to be on `devel` branches (or use something like `wstool merge https://raw.githubusercontent.com/jhu-saw/sawNDITracker/devel/ros/ndi_tracker.rosinstall`).

**Comment by jsbyysheng** [comment]
I still got:
```
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame 01-38007400-610066---T6d0-S00136 at time 1640067402.040424 according to authority /saw_ndi_tracker_1640067223709691039
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame 02-37BB9000-610065---T6e0-S00066 at time 1640067402.067759 according to authority /saw_ndi_tracker_1640067223709691039
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame 02-37BB9000-610065---T6e0-S00066 at time 1640067402.092629 according to authority /saw_ndi_tracker_1640067223709691039
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame 02-37BB9000-610065---T6e0-S00066 at time 1640067403.616457 according to authority /saw_ndi_tracker_1640067223709691039
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
```
I tested the patch by running `rosrun tf view_frames`.

**Comment by adeguet1** [comment]
Sorry the first patch didn't fix the issue, I didn't have a Noetic install handy.  I thought the problem was related to the timestamp but it seems it was related to 2 tf broadcasters trying to send transforms with the same child id but different header frame id.  I assumed this was supported by tf but it is not since tf only supports trees (on frame can have multiple children but a child can only have one parent).  Annoyingly, tf doesn't give you any error nor warning if the parent frame id has changed.  This is odd since they took the time to add a warning if the timestamp is the same.  I tested this patch on Noetic with another device but I hope the patch will work for sawNDITracker.  See https://github.com/jhu-cisst/cisst-ros/commit/623eb0706a863200096af95dfa61403b61b00994
